### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by imlove** [idiotWu/angular-smooth-scrollbar#10]
Uncaught TypeError: Cannot read property 'version' of undefined
    at angular-smooth-scrollbar.js:20
    at angular-smooth-scrollbar.js:8
    at angular-smooth-scrollbar.js:10

**Comment by idiotWu** [comment]
Have you imported the `smooth-scrollbar` library?

**Comment by imlove** [comment]
yes,
I used `oclazyload` to dynamically load both `smooth-scrollbar` and `angular-smooth-scrollbar`.
Sometimes not wrong, but most of the time there will be this mistake

**Comment by imlove** [comment]
I guess this may be the wrong loading sequence

**Comment by shennero** [comment]
Where can I find the smooth-scrollbar library?  I downloaded the zip but only see the angular-smooth-scrollbar file in the dist folder.

**Comment by idiotWu** [comment]
@shennero https://github.com/idiotWu/smooth-scrollbar

**Comment by shennero** [comment]
@idiotWu thanks!  It works great.
