### ISSUE TITLE
Determine how much user has scrolled

### ISSUE THREAD

**Issue by sadashivm** [idiotWu/angular-smooth-scrollbar#11]
Hi,
Determine how much user has scrolled the page in pixel i mean scrolled amount because i want to show "Scroll to Top" button in page and also if i click that button it should goes to top.

i written bellow code 

```
var offset = 300;
$(window).scroll(function () {
if($(this).scrollTop() > offset) {
$('#scrollTop').show();
}
else {
$('#scrollTop').hide();
}
            });
```

but problem is im not getting $(this).scrollTop() value.
if i use default browser then i will get value but i use this scrollbar then above code is not working.

for reference find the screenshot

![back to top](https://cloud.githubusercontent.com/assets/10355473/21515038/2bf1b6fc-ccf2-11e6-99b0-f0cc2aedb581.png)

i  want to implement above button with your scrollbar. can u tell me how to do it.

**Comment by idiotWu** [comment]
Read [docs](https://github.com/idiotWu/smooth-scrollbar/wiki/Instance-Methods) again and you'll find the answer.
