### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by javadbat** [idiotWu/angular-smooth-scrollbar#2]
i need update function of your scroll bar but the guid you write is not clear about that and so confusing

**Comment by idiotWu** [comment]
Do you mean README guide?

**Comment by javadbat** [comment]
hi
you made a good scroll bar but about user guid to use it its so confusing
please explain more about feature and setting .
for example see this jalali calender component :
https://github.com/babakhani/pwt.datepicker
when i read your documentation i dont understand what is
instance#update( cb )
mean?
how i can use it ?
thank you :)

**Comment by idiotWu** [comment]
Thanks for the advice. Since this is a WIP project, I don't really want to rewrite user guide right now:)

**Comment by javadbat** [comment]
:) i search entire web and there is no better scroll plugin than yours i
hope best for you

**Comment by idiotWu** [comment]
I've made `smooth-scrollbar` an universal module and rewrite docs [here](https://github.com/idiotWu/smooth-scrollbar#apis) :tada:
