### ISSUE TITLE
Proposal for new feature

### ISSUE THREAD

**Issue by brunowego** [idiotWu/angular-smooth-scrollbar#5]
Think about a option to scroll to top when user leave the scroll. I get this issue when use this plugin with a navbar.

**Comment by brunowego** [comment]
More details about the issue:

![issue](https://cloud.githubusercontent.com/assets/441774/14531260/f325003e-0232-11e6-8793-1f4629d9be04.gif)

**Comment by idiotWu** [comment]
You mean scrollbar scrolls to top when it's inactive? However I have no way to know the status of your app, currently scrollbar will scroll to top when the `scope` is destroyed [index.js#L153](https://github.com/idiotWu/angular-smooth-scrollbar/blob/master/index.js#L153).

**Comment by brunowego** [comment]
Thanks @idiotWu, this information was enough.
