### ISSUE TITLE
Does this work with ng-view ?

### ISSUE THREAD

**Issue by midaspider** [idiotWu/angular-smooth-scrollbar#6]
I've tried using it in a few places inside and outside my ng-view div and can't get it to work.

I'm using AngularJS v1.4.9

**Comment by idiotWu** [comment]
Sure it does! Actually I was working on an angular based SPA when I started this plugin.

I suppose that you are suffering same issue with idiotWu/smooth-scrollbar#19. Or can you provide a demo about this?
