### ISSUE TITLE
Unable to find suitable version for angular - on bower install

### ISSUE THREAD

**Issue by shooby83** [idiotWu/angular-smooth-scrollbar#7]
My bower.json looks as folowing:
{
  "name": "uiApp",
  "version": "0.0.0",
  "dependencies": {
    "angular-animate": "~1.5.3",
    "angular-cookies": "~1.5.3",
    "angular-touch": "~1.5.3",
    "angular-sanitize": "~1.5.3",
    "jquery": "~2.1.4",
    "angular-resource": "~1.5.3",
    "angular-ui-router": "~0.2.15",
    "bootstrap-sass": "~3.3.5",
    "angular-bootstrap": "~1.3.3",
    "malarkey": "yuanqing/malarkey#~1.3.1",
    "angular-toastr": "~1.5.0",
    "moment": "~2.10.6",
    "animate.css": "~3.4.0",
    "angular": "~1.5.3",
    "angular-translate": "^2.11.1",
    "angular-translate-loader-static-files": "^2.11.1",
    "angular-oauth2": "^4.0.0"
  },
  "devDependencies": {
    "angular-mocks": "~1.5.3"
  },
  "overrides": {
    "bootstrap-sass": {
      "main": [
        "assets/stylesheets/_bootstrap.scss",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.eot",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.svg",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.ttf",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.woff",
        "assets/fonts/bootstrap/glyphicons-halflings-regular.woff2"
      ]
    }
  },
  "resolutions": {
    "jquery": "~2.1.4",
    "angular": "~1.5.3"
  }
}

bower install angular-smooth-scrollbar --save failes. 

Any ideas how to solve this? The plugin looks pretty promising and I really want to try it.

Thanks.

Matthias

**Comment by idiotWu** [comment]
![2016-09-19 17 52 08](https://cloud.githubusercontent.com/assets/6022672/18626753/d2d048ee-7e91-11e6-93cb-49f5257ae476.png)

However in my test it was passed...

Have you ever been asked for a version choice for angular? I suppose there's an old version of scrollbar in installed bower components, you can either try `rm -rf bower_components && bower install` or choose your answer to the version choice.

**Comment by idiotWu** [comment]
Closed as no response.
