### ISSUE TITLE
Slow Scrolling on FF - is back 

### ISSUE THREAD

**Issue by georgebatalinski** [idiotWu/angular-smooth-scrollbar#8]
**I am currently on:** 
FF - 50
"angular-smooth-scrollbar": "^7.2.0",

**Same as**
[Issue #3](https://github.com/idiotWu/angular-smooth-scrollbar/issues/3)

**Steps to reproduce**
Scroll down/up down (either PageUp/Down buttons or Mousewheel)
Result: you will get very leggy performance 

Any suggestions, why this may still be happening in "angular-smooth-scrollbar": "^7.2.0",?

**Comment by idiotWu** [comment]
I though the behavior is different from that is in issue #3. 

Firefox has a poor performance on large layers rendering, **DON'T** try to use smooth-scrollbar with huge areas.

**Comment by georgebatalinski** [comment]
Thank you
